---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: jenkins
rules:
- apiGroups: ["extensions","apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch","create","update","patch","delete"]
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - namespaces
  - namespace
  - deployments
  - extensions
  - deployments.extensions
  - clusterroles
  - ClusterRoleBinding
  verbs: ["get", "list", "watch","create","update","patch","delete"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get","list"]
